### ISSUE TITLE
selinux should be enabled by this role

### ISSUE THREAD

**Issue by laishulu** [johanmeiring/ansible-sftp#15]
this role require selinux, but does not config selinux for users.
can you add script to enable selinux?

**Comment by johanmeiring** [comment]
selinux isn't required in order to use this role.  The reference to selinux was added in order to cater to users of Centos etc where selinux is likely already installed.  The configuration of an existing selinux setup happens here: https://github.com/johanmeiring/ansible-sftp/blob/master/tasks/main.yml#L29

I think installing and enabling selinux falls outside the scope of this role, because it isn't inherently required in order for SFTP to work.  Best I'm willing to do for now is to implement #14 for cases where selinux has already been installed on an ubuntu target (unless of course you can make a stronger argument :) ).

I'll leave this issue open for additional comments for now.

**Comment by joshribakoff** [comment]
I agree with @johanmeiring it would be confusing to install an sFTP role & unknowingly have it enable selinux. Enabling selinux on a production box could break existing features, so it should not happen by default.
