### ISSUE TITLE
Allow usage for external servers

### ISSUE THREAD

**Issue by kalioz** [johanmeiring/ansible-sftp#38]
Hi !
We used to use this role exclusively on `localhost` and, while I was trying to migrate to execute it on multiple servers (one 'server' and multiple 'clients') I found out I couldn't due to the [use of a lookup](https://github.com/johanmeiring/ansible-sftp/blob/master/tasks/main.yml#L87), which only executes on the host executing the ansible script, and therefore cannot find the files who have been created on the clients.

I've created a workaround using slurp, but I was wondering if it was me who misunderstood how to use this module ? I'll create a PR if this is not the case. 

Thanks,

**Comment by kalioz** [comment]
i've created the PR to not forget about it and so that someone can test it / use it if they want to.

**Comment by johanmeiring** [comment]
Hi @kalioz !  When you say "server", are you referring to the Ansible control node (i.e. the machine that the Ansible playbook is being run on), or something else?  Please help me understand your scenario a little better.

**Comment by kalioz** [comment]
Hi @johanmeiring , yes by server I mean control node. 
The use of lookup('file') means you need to have the public keys files on the control node when they are created and used on the managed node.

**Comment by johanmeiring** [comment]
Yup, that's perfectly fine.  It means that the playbook that uses this role must have the keys included as part of it.  The typical directory structure for such a playbook might look something like this:

```
/
  playbook.yml
  hosts
  /files
    key1.pub
    key2.pub
    ...
  /roles
    // Various roles installed via ansible-galaxy, including this one.
  /vars
    main.yml
```

My understanding is that most users of this role either follow the above pattern, or specify hashed passwords.

Your idea of using `slurp` is good though, but it would break BC pretty hard I think.  Perhaps consider detecting whether or not the element in `authorized` needs to be slurped instead of looked up by checking if it starts with `http`?  What do you think?

**Comment by kalioz** [comment]
From what you describe I think our workflow is different from yours, we generate the ssh keys and user folders in the managed node before using your script (vs having the ssh keys in the control node).
It would indeed be a breaking change in the current state but could be modified to allow for both use-case, i'll try to modify it when i can.
Thank you for your explanations !
